services:
  - type: web
    name: online-shopping-app
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: CLOUDINARY_URL
        sync: false 